### ISSUE TITLE
Référence légale incorrecte

### ISSUE THREAD

**Issue by Bibi56** [pixeye33/unkm.fr#14]
"texte de la loi en vigueur" fait référence à la loi de mars (abrogée).
Celle de mai est ici : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000041865244&categorieLien=id mais la distance de 100 km se trouve dans le décret : https://www.legifrance.gouv.fr/eli/decret/2020/5/11/SSAZ2011695D/jo/texte

**Comment by pixeye33** [comment]
C'est bien vu, et corrigé à présent : https://github.com/pixeye33/unkm.fr/commit/f52970f9817585da9c22f5a52f5f2b77aadcd8b5 !

Merci :)
